// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzePlaylist(arg1:string):Promise<string>;

export function AnalyzeURL(arg1:string):Promise<string>;

export function AutoSaveSettings():Promise<void>;

export function CancelConversion():Promise<void>;

export function CancelDownload():Promise<void>;

export function ConvertVideo(arg1:string,arg2:string):Promise<void>;

export function DownloadPlaylist(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<void>;

export function DownloadVideo(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetActualDownloadPath(arg1:string):Promise<string>;

export function GetDownloadDirectory():Promise<string>;

export function GetDownloadPath(arg1:string):Promise<string>;

export function GetLatestYtDlpVersion():Promise<string>;

export function GetPlaylistItems(arg1:string):Promise<string>;

export function GetSettings():Promise<string>;

export function GetYtDlpVersion():Promise<string>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function SelectDownloadDirectory():Promise<string>;

export function SetDownloadDirectory(arg1:string):Promise<void>;

export function SetupDependencies():Promise<void>;

export function UpdateAutoRedirectToQueue(arg1:boolean):Promise<void>;

export function UpdateLanguage(arg1:string):Promise<void>;

export function UpdateSettingsWithCookiesFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdateYtDlp():Promise<void>;

export function ValidateCookiesFile(arg1:string):Promise<boolean>;
