// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzePlaylist(arg1) {
  return window['go']['main']['App']['AnalyzePlaylist'](arg1);
}

export function AnalyzeURL(arg1) {
  return window['go']['main']['App']['AnalyzeURL'](arg1);
}

export function AutoSaveSettings() {
  return window['go']['main']['App']['AutoSaveSettings']();
}

export function CancelConversion() {
  return window['go']['main']['App']['CancelConversion']();
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ConvertVideo(arg1, arg2) {
  return window['go']['main']['App']['ConvertVideo'](arg1, arg2);
}

export function DownloadDeno() {
  return window['go']['main']['App']['DownloadDeno']();
}

export function DownloadPlaylist(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DownloadPlaylist'](arg1, arg2, arg3, arg4, arg5);
}

export function DownloadVideo(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadVideo'](arg1, arg2, arg3);
}

export function GetActualDownloadPath(arg1) {
  return window['go']['main']['App']['GetActualDownloadPath'](arg1);
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetDenoVersion() {
  return window['go']['main']['App']['GetDenoVersion']();
}

export function GetDownloadDirectory() {
  return window['go']['main']['App']['GetDownloadDirectory']();
}

export function GetDownloadPath(arg1) {
  return window['go']['main']['App']['GetDownloadPath'](arg1);
}

export function GetLatestDenoVersion() {
  return window['go']['main']['App']['GetLatestDenoVersion']();
}

export function GetLatestVersion() {
  return window['go']['main']['App']['GetLatestVersion']();
}

export function GetLatestYtDlpVersion() {
  return window['go']['main']['App']['GetLatestYtDlpVersion']();
}

export function GetPlaylistItems(arg1) {
  return window['go']['main']['App']['GetPlaylistItems'](arg1);
}

export function GetReleaseNotes() {
  return window['go']['main']['App']['GetReleaseNotes']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetUpdateDownloadUrl() {
  return window['go']['main']['App']['GetUpdateDownloadUrl']();
}

export function GetYtDlpVersion() {
  return window['go']['main']['App']['GetYtDlpVersion']();
}

export function InstallDeno() {
  return window['go']['main']['App']['InstallDeno']();
}

export function IsDenoAvailable() {
  return window['go']['main']['App']['IsDenoAvailable']();
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function SelectDownloadDirectory() {
  return window['go']['main']['App']['SelectDownloadDirectory']();
}

export function SetDownloadDirectory(arg1) {
  return window['go']['main']['App']['SetDownloadDirectory'](arg1);
}

export function SetupDependencies() {
  return window['go']['main']['App']['SetupDependencies']();
}

export function ShouldUpdate() {
  return window['go']['main']['App']['ShouldUpdate']();
}

export function UpdateAutoRedirectToQueue(arg1) {
  return window['go']['main']['App']['UpdateAutoRedirectToQueue'](arg1);
}

export function UpdateDeno() {
  return window['go']['main']['App']['UpdateDeno']();
}

export function UpdateJSRuntimeSetting(arg1) {
  return window['go']['main']['App']['UpdateJSRuntimeSetting'](arg1);
}

export function UpdateLanguage(arg1) {
  return window['go']['main']['App']['UpdateLanguage'](arg1);
}

export function UpdateSettingsWithCookiesFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateSettingsWithCookiesFile'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateYtDlp() {
  return window['go']['main']['App']['UpdateYtDlp']();
}

export function ValidateCookiesFile(arg1) {
  return window['go']['main']['App']['ValidateCookiesFile'](arg1);
}
